[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[project]
readme = "README.md"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
